version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3333:3000
    volumes:
      - /root/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - /root/docker/homepage/images:/app/public/images
    env_file:
      - /root/docker/homepage/secrets.env
    restart: always
